Lets fix a pipeline so its broken in a normal way

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -28,7 +28,7 @@ jobs:
       - name: Authenticate with GCP
         uses: google-github-actions/auth@v1
         with:
-          credentials_json: ${{ secrets.GCP_SA_KEY }}
+          credentials: ${{ secrets.GCP_SA_KEY }}
 
       - name: Set up Google Cloud SDK
         uses: google-github-actions/setup-gcloud@v1.1.0
@@ -50,11 +50,10 @@ jobs:
             fi
           done
           if [ ${#changed_dirs[@]} -eq 0 ]; then
-            echo "No changes detected. Subsequent steps will not run automatically."
-            echo "::set-output name=no_changes_detected::true"
-          else
-            echo "::set-output name=changed_dirs::${changed_dirs[@]}"
+            echo "No changes detected. Manual deployment required."
+            exit 78
           fi
+          echo "::set-output name=changed_dirs::${changed_dirs[@]}"
 
       - name: Build and push Docker image
         if: contains(steps.check-changes.outputs.changed_dirs, ${{ matrix.service }})
@@ -69,12 +68,14 @@ jobs:
         with:
           cluster_name: ${{ env.GKE_CLUSTER }}
           location: ${{ env.GKE_ZONE }}
-          credentials_json: ${{ secrets.GCP_SA_KEY }}
+          credentials: ${{ secrets.GCP_SA_KEY }}
 
       - name: Deploy to Kubernetes
-        if: contains(steps.check-changes.outputs.changed_dirs, ${{ matrix.service }}) && !{{ steps.check-changes.outputs.no_changes_detected }}
+        if: contains(steps.check-changes.outputs.changed_dirs, ${{ matrix.service }})
         run: |
           envsubst < ./${{ matrix.service }}/k8s/${{ matrix.service }}.yml | kubectl apply -f -
 
       - name: Verify deployment
-        if: contains(steps.check-changes.outputs.changed_dirs, $
+        if: contains(steps.check-changes.outputs.changed_dirs, ${{ matrix.service }})
+        run: |
+          kubectl rollout status deployment/${{ matrix.service }} -n $K8S_NAMESPACE
